[package]
name = "diesel-d1-api"
version = "0.1.0"
edition = "2024"
description = "Diesel D1 via the http API"
license-file = "../LICENSE"
homepage = "https://github.com/hydrogen602/diesel-d1"
authors = ["Jonathan Rotter <contact@hydrogen602.com>"]


[dependencies]
diesel = { workspace = true, features = [
  "i-implement-a-third-party-backend-and-opt-into-breaking-changes",
] }
diesel-d1-core = { path = "../diesel-d1-core" }
diesel-async = { workspace = true }
futures-util = "0.3.34"
itertools = "0.15.0"
thiserror = "2.0.20"
reqwest = { version = "0.13.5", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
uuid = "1.26.0"
urlencoding = "2.1.3"
