[package]
name = "diesel-d1"
version = "0.2.0"
edition = "2024"
authors = [
    "Jonathan Rotter <contact@hydrogen602.com>",
    "Luís Duarte <lduarte@cloudflare.com>",
]
license-file = "../LICENSE"
homepage = "https://github.com/hydrogen602/diesel-d1"
description = "A Diesel Backend/Connection for Cloudflare D1."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
diesel = { workspace = true, features = [
    "i-implement-a-third-party-backend-and-opt-into-breaking-changes",
] }
diesel-d1-core = { path = "../diesel-d1-core", features = ["worker"] }
diesel-async = { workspace = true }
futures-util = "0.3.34"
itertools = "0.15.0"
js-sys = "0.3.74"
thiserror = "2.0.20"
wasm-bindgen = "0.2.127"
wasm-bindgen-futures = "0.4.77"
worker = { workspace = true }
