#!/usr/bin/env python3

# Generated by integration-tester/src/bin/gen_py_tests.rs
import unittest
import urllib.request

BASE_URL = 'http://localhost:8787/'

class TestIntegration(unittest.TestCase):

  def test_users(self):
    with urllib.request.urlopen(f'{BASE_URL}test_users') as response:
      self.assertEqual(response.read().decode('utf-8'), 'test_users passed')


if __name__ == '__main__':
    unittest.main()
